name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.2.1
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-snake.svg
            ./assets/github-snake-dark.svg?palette=github-dark
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: main
          author_name: Jinx
          author_email: jinhaidi01@gmail.com
          message: "Generate Contribution Snake"